# https://github.com/ralexander-phi/marp-to-pages/blob/main/.github/workflows/marp-to-pages.yml

---
name: marp-to-pages
on:
  push:
    paths:
      - '**/*.md'

jobs:

  update_index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate HTML
      run: |
        cd docs
        sed -i "/item float-item/d" index.html
        for input in *.md; do
           sed -i -e "s|<!-- STOP-LIST -->|<a href='${input%.*}.html'><li class='item float-item'>${input%.*}</li></a>\n\t<!-- STOP-LIST -->|g" index.html
        done
    - name: Commit index
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html
        git commit -m "Generated index.html" || true
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

  update_readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate README.md
      run: |
        echo '# [Prez](https://kayoo123.github.io/Prez/):' > README.md
        echo -e '| Markdown(edit) | PDF   | HTML |\n| :------: | :---: | :---:|' >> README.md
        for input in docs/*.md; do
          filename=$(basename -s .md $input)
          echo "| [${filename}.md](https://github.com/kayoo123/Prez/edit/main/docs/${filename}.md) | [${filename}.pdf](https://kayoo123.github.io/Prez/${filename}.pdf) | [${filename}.html](https://kayoo123.github.io/Prez/${filename}.html)" >> README.md
        done
    - name: Commit README.md
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Generated README.md" || true
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

  build_html-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install MARP
      run: |
        curl -L https://github.com/marp-team/marp-cli/releases/download/v2.3.0/marp-cli-v2.3.0-linux.tar.gz | tar xz
        sudo mv marp /usr/local/bin
    - name: Generate HTML
      run: |
        cd docs
        marp --html *.md
    - name: Generate PDF
      run: |
        cd docs
        marp --pdf *.md
    - name: Commit HTML & PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/*.html
        git add docs/*.pdf
        git commit -m "Generated HTML & PDF"
        git pull --rebase
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
