# https://github.com/ralexander-phi/marp-to-pages/blob/main/.github/workflows/marp-to-pages.yml

---
name: marp-to-pages
on:
  push:
    paths:
      - '**/*.md'

jobs:

  update_index:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Generate HTML
      run: |
        for input in docs/*.md; do
          echo $input
        done
    - name: Commit index
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/index.html
        git commit -m "Generated HTML & PDF"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
    
  build_html-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install MARP
      run: |
        curl -L https://github.com/marp-team/marp-cli/releases/download/v2.3.0/marp-cli-v2.3.0-linux.tar.gz | tar xz
        sudo mv marp /usr/local/bin
    - name: Generate HTML
      run: |
        cd docs
        marp --html *.md
    - name: Generate PDF
      run: |
        cd docs
        marp --pdf *.md
    - name: Commit HTML & PDF
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add docs/*.html
        git add docs/*.pdf
        git commit -m "Generated HTML & PDF"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
