# https://github.com/ralexander-phi/marp-to-pages/blob/main/.github/workflows/marp-to-pages.yml

---
name: marp-to-pages
on:
  push:
    paths:
      - '**/*.md'

jobs:

  update_index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Update index.html
        run: |
          for input in *.md
          do
            echo "<a href=\"$input.html\"><li class=\"item float-item\">$input</li></a>" >> docs/index.html
          done
      - name: Commit Index
        run: |
          git config --global user.email "jeri.dsql@gmail.com"
          git config --global user.name "kayoo123"
          git add docs/index.html
          git commit -m "Update index.html"

  build_html:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build HTML
        uses: docker://marpteam/marp-cli:v2.3.0
        with:
          args: test.md -o docs/test.html
        env:
          MARP_USER: root:root
      - name: Commit html
        run: |
          git config --global user.email "jeri.dsql@gmail.com"
          git config --global user.name "kayoo123"
          git add docs/*.html
          git commit -m "Update *.html"
