# https://github.com/ralexander-phi/marp-to-pages/blob/main/.github/workflows/marp-to-pages.yml

---
name: marp-to-pages
on:
  push:
    paths:
      - '**/*.md'

jobs:

  build_html-pdf:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install MARP
      run: |
        curl -L https://github.com/marp-team/marp-cli/releases/download/v2.3.0/marp-cli-v2.3.0-linux.tar.gz | tar xz
        sudo mv marp /usr/local/bin
    - name: Generate HTML & PDF
      run: |
        marp --html --pdf *.md --output-dir docs
    - name: Commit HTML & PDF
      run: |
        git add docs/*.html
        git add docs/*.pdf
        git commit -m "Generated HTML & PDF"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
